### ISSUE TITLE
Out-of-date version of fabric-sdk

### ISSUE THREAD

**Issue by sg3des** [chainHero/heroes-service#1]
it`s useful tutorial\example, but why you use older version of fabric-sdk, there are some reasons for this? 

In the current version of sdk, package `util` not exist, it was be removed on commit - [[FAB-4890] Fabric Txn API and removed utils](https://github.com/hyperledger/fabric-sdk-go/commit/4bb3690f54a01d3748f8d001039744ab86234d95).

Thx.

**Comment by xuchenhao001** [comment]
Agree with @sg3des . Could you please give an another example based on latest version's `fabric-sdk-go`? Thanks!

**Comment by antitoine** [comment]
@sg3des and @xuchenhao001, we will work on it this week. Updating the tutorial is a long process, we have run out of time so far.

**Comment by antitoine** [comment]
@sg3des and @xuchenhao001 the new version was merged on master (#4). If you have any suggestions, don't hesitate to come back to me.
