### ISSUE TITLE
How can I list all of the peers in a channel?

### ISSUE THREAD

**Issue by xuchenhao001** [chainHero/heroes-service#10]
Thanks for your sample! That makes me easier to use `fabric-go-sdk`.(about join channel, install chaincode, instantiate, invoke and query)
However, I want to build a more complex application through this SDK, for example, list all of the peers in a channel. How to do so?
Thanks!

**Comment by MaximeAubanel** [comment]
Hello Sir,

At the moment it's not possible to do it within the Fabric SDK Go.

However, this feature is being currently in active development as you can see [here](https://jira.hyperledger.org/browse/FAB-8779).

**Comment by antitoine** [comment]
Hi @xuchenhao001, 
It is possible to discover the peers that there are in a channel. However, this service is in an embryonic state. For this you need to use the Discovery Service of the SDK:

```golang
chClCtx, err := sdk.ChannelContext("Channel_ID", fabsdk.WithUser("User_ID"), fabsdk.WithOrg("Org_ID"))()
if err != nil {
	return nil, errors.WithMessage(err, "failed to get client channel context")
}
peers, err := chClCtx.DiscoveryService().GetPeers()
```

For your second point, you need to change your SDK context to instantiate the chaincode with the second organization.

I close this ticket as it is not related to the tutorial. But I invite you to communicate with the community on the chat: http://chat.hyperledger.org/
