### ISSUE TITLE
make depend-install fail

### ISSUE THREAD

**Issue by jks1995** [chainHero/heroes-service#12]
When i run the make depend-install it says I am missing some dependencies. I went through and did a go get for all the dependencies listed but it still returns the same error. How should I proceed?

**Comment by MaximeAubanel** [comment]
Hey !

Would you please tell us : 
- Your Operation System
- Your version of Go

Are you speaking about running ```make depend-install``` within the SDK Go folder ? If so, I probably won't be able to help you efficiently because it would mean that the issue is coming from the SDK Go.

**Comment by jks1995** [comment]
Thanks for responding. go version go1.10 darwin/amd64 on osx! and yes it is within the go sdk. do you know where i could go to ask for help? ive also posted in the fabric rocketchat.

**Comment by jks1995** [comment]
also screenshot
<img width="1311" alt="screen shot 2018-06-02 at 9 45 25 am" src="https://user-images.githubusercontent.com/19289646/40879028-f2cca4fc-6667-11e8-8eaf-4c9cdd61c1bf.png">

**Comment by MaximeAubanel** [comment]
Hey jks1995,

I'm sorry but I'm not able to provide you any response. I would advise you to send a message again on the fabric rocketchat in the SDK Go room.

**Comment by jks1995** [comment]
if I echo $GOPATH it gives me the path back a path I expect. any other ideas on what to do?

**Comment by MaximeAubanel** [comment]
Where did you create the repository ? May you go in the heroes-service folder that you created and execute `pwd`. Paste it here then.
