### ISSUE TITLE
compilation issue Fabric SDK Go at the Test Step 

### ISSUE THREAD

**Issue by M-AMAIRI** [chainHero/heroes-service#13]
Hi , 

I followed the tutorial, and I installed Version Go 1.10, but I have some problem of compilation, in my opinion because of a missing library , despite I have succeeded in all precedent steps .
here is the echo when launching build 

```
cd $GOPATH/src/github.com/chainHero/heroes-service && go build
main.go:6:2: cannot find package "github.com/chainHero/heroes-service/web" in any of:
	/home/m-amairi/go/src/github.com/chainHero/heroes-service/vendor/github.com/chainHero/heroes-service/web (vendor tree)
	/usr/local/go/src/github.com/chainHero/heroes-service/web (from $GOROOT)
	/home/m-amairi/go/src/github.com/chainHero/heroes-service/web (from $GOPATH)
main.go:7:2: cannot find package "github.com/chainHero/heroes-service/web/controllers" in any of:
	/home/m-amairi/go/src/github.com/chainHero/heroes-service/vendor/github.com/chainHero/heroes-service/web/controllers (vendor tree)
	/usr/local/go/src/github.com/chainHero/heroes-service/web/controllers (from $GOROOT)
	/home/m-amairi/go/src/github.com/chainHero/heroes-service/web/controllers (from $GOPATH)
```

can someone help me please ,
thanks ,
Moatez

**Comment by MaximeAubanel** [comment]
Hi @M-AMAIRI !

It's not a problem of dependencies but a problem with your files. The error is saying that you don't have the web files in your directories.

Can you tell me where did this issue came ? At which point of the tutorial ?

**Comment by antitoine** [comment]
@M-AMAIRI ,
You must have copied the `Gopkg.lock` file in addition to the `Gopkg.toml`. Remove the `Gopkg.lock` file, run the dependency manager and compile again: 
```bash
cd $GOPATH/src/github.com/chainHero/heroes-service
rm -f Gopkg.lock
dep ensure
go build
```

**Comment by antitoine** [comment]
I close this issue as there was no update.

**Comment by M-AMAIRI** [comment]
Hi @antitoine  , thank you for help , Sorry for the Late Reply I have been sick since last week , I followed the steps that you mentioned, and currently it works for me , and as @MaximeAubanel  said , this type of errors can be also by the lack of  web/controllers files .

Thanks ,
Moatez ,
