### ISSUE TITLE
unable to verify if cc is installed

### ISSUE THREAD

**Issue by freemking** [chainHero/heroes-service#16]
**As the below, what's wrong with it, thank you!**
![1529251377082](https://user-images.githubusercontent.com/3021656/41509730-fb8a3a58-728a-11e8-9f19-334c6947e38a.jpg)

**Comment by MaximeAubanel** [comment]
Hey @freemking,

Sorry, this version is still under development and currently not working.

Use our last working version : [heroes-service.v1.0.5]( https://github.com/chainHero/heroes-service/tree/v1.0.5)

Have a great day !
Maxime
