### ISSUE TITLE
Unable to install and instantiate the chaincode

### ISSUE THREAD

**Issue by freemking** [chainHero/heroes-service#17]
I tried the v1.0.5, but that's reporting that Unable to install and instantiate the chaincode.
![image](https://user-images.githubusercontent.com/3021656/41519526-3ba105c0-72fb-11e8-9fb5-63d8fdb3abc5.png)

**Comment by MaximeAubanel** [comment]
Hello @freemking,

Please provide us your :

- Go version
- Docker version
- Operating system

Are you using an Ubuntu VM on a Mac OSX ?

Have a great day,
Maxime

**Comment by freemking** [comment]
Hi @MaximeAubanel 

- Go version: 1.10.3
- Docker version: 17.12.0-ce
- Operating system: Max OSX

I just use Max OSX.
But when i use `make clean` and retry `make`, it's ok now.

**Comment by freemking** [comment]
@MaximeAubanel 
Yes, you can close it, thank you!
