### ISSUE TITLE
CC Initialization Failed

### ISSUE THREAD

**Issue by donleemalacad** [chainHero/heroes-service#22]
Hi i tried v1.1 but i'm experiencing this error

> Failed to instantiate the chaincode: failed to get discovery service: could not get chConfig cache reference: QueryBlockConfig failed: target(s)required

System Specs:

Ubuntu 18.04 LTS (VM)
Docker  Version: 18.03.1-ce
Go version go1.10.2

        ccPolicy := cauthdsl.SignedByAnyMember([]string{"org1.hf.chainhero.io"})

	// Org resource manager will instantiate chaincode on channel
	resp, err := setup.resClient.InstantiateCC(setup.ChannelID, resmgmt.InstantiateCCRequest{ Name: setup.ChainCodeID, Path: setup.ChaincodeGoPath, Version: "0", Args: [][]byte{[]byte("init")}, Policy: ccPolicy, },)

	if err != nil || resp.TransactionID == "" {
		return errors.WithMessage(err, "Failed to instantiate the chaincode")
	}
`

**Comment by antitoine** [comment]
Hi,
Can I see your configuration file (`config.yaml`)?
I get the impression you didn't specify the peers.
The channel is initialized correctly ?

**Comment by malacdon** [comment]
Hi @antitoine . thank you for the fast response. You are right. I dont know why but peer0 is set at wrong address in config.yaml.


     channels:
         // name of the channel
         chainhero:

         // Required. list of peers from participating orgs
         peers:
             peer0.org1.example.com: <-----

@antitoine  Thank you very much.

**Comment by antitoine** [comment]
You're welcome!
