### ISSUE TITLE
Chaincode Instantiate error

### ISSUE THREAD

**Issue by stanly-johnson** [chainHero/heroes-service#28]
sudo make

Stop environment ...
Removing network fabsdkgo_default
WARNING: Network fabsdkgo_default not found.
Environment down
Clean up ...
Clean up done
Build ...
Build done
Start environment ...
Creating network "fabsdkgo_default" with the default driver
Creating orderer.hf.chainhero.io ... done
Creating ca.org1.hf.chainhero.io    ... done
Creating peer1.org1.hf.chainhero.io ... done
Creating peer0.org1.hf.chainhero.io ... done
Environment up
Start app ...
SDK created
Ressource management client created
Channel created
Channel joined
Initialization Successful
ccPkg created
Chaincode installed
Unable to install and instantiate the chaincode: failed to instantiate the chaincode: Chaincode name, version, path and policy are required

I git this error every time I try to run chaincode

**Comment by antitoine** [comment]
Hi,

Why `sudo make`?
It is a general advice, avoid using `sudo` for an application (especially if you don't know the origin of the application).
Maybe you use it for docker? If so, you did not install Docker correctly: https://github.com/chainHero/heroes-service#linux-ubuntu and logout/login after.

That being said, your problem doesn't seem to come from that but from the configuration you put in the YAML file. Check your configuration and code. To be sure, clone the repository in another place and run `make`.

**Comment by stanly-johnson** [comment]
Thanks, @antitoine. I simply cloned the repo and ran the command. I did not make any modifications.

**Comment by antitoine** [comment]
Great!
