### ISSUE TITLE
Generating fixtures/

### ISSUE THREAD

**Issue by Jeff-Zoch** [chainHero/heroes-service#5]
I read (and thoroughly enjoyed) the blog post and saw that a future post would cover how to generate the files in fixtures/. Any timeline on this? I like the structure of this demo a lot and would love to use it for a project but don't know how to generate my own fixtures/ (i tried the generator.sh script in the fabric docs, but no dice). Publishing the script used would be very useful!

**Comment by antitoine** [comment]
Hi @Jeff-Zoch, thank you for this encouraging feedback! We still need some explanations to publish this little guide on the creation of the fixtures folder. I hope that by the end-of-week it will be online.
In the meantime, here's some help:
 - Follow the tutorial of Fabric and look at the content of the `byfn.sh` script : https://hyperledger-fabric.readthedocs.io/en/release-1.0/build_network.html
 - Download binaries that match your Fabric version here : https://nexus.hyperledger.org/content/repositories/releases/org/hyperledger/fabric/hyperledger-fabric/
 - Create your own `crypto-config.yaml` and `configtx.yaml` with instructions you can find here: https://hyperledger-fabric.readthedocs.io/en/release-1.0/build_network.html#how-does-it-work
 - Then run:
```
mkdir -p crypto-config
./bin/cryptogen generate --config=./crypto-config.yaml
mkdir -p artifacts
./bin/configtxgen -profile YourProfile -outputBlock ./artifacts/orderer.genesis.block
./bin/configtxgen -profile YourProfile -outputCreateChannelTx ./artifacts/channel.tx -channelID YourChannel
./bin/configtxgen -profile YourProfile -outputAnchorPeersUpdate ./artifacts/org1.anchors.tx -channelID YourChannel -asOrg YourOrg1
```

I hope this will help you.

**Comment by Jeff-Zoch** [comment]
Super helpful thank you! I cant seem to write the correct configtx.yaml (I keep getting MSP org1.hf.chainhero.com is unknown) but Ill look out for the blog.

**Comment by antitoine** [comment]
We have some delay on the production of the blog article, I hope it will come out as soon as possible. If you have any questions please feel free to ask me directly here to help you move forward.
To try to answer your problem, look at the domains present in `crypto-config.yaml` file. Then, check the part `Organizations.<Org Name>.ID` in the `configtx.yaml` file that define the MSP ID.

**Comment by antitoine** [comment]
We just published the little tutorial here: https://chainhero.io/2018/04/tutorial-hyperledger-fabric-how-to-build-your-first-network/
Feel free to give your feedback or contribute if you have ideas.
