### ISSUE TITLE
can't locate chainhero.channel.tx: no such file or directory

### ISSUE THREAD

**Issue by beshogun** [chainHero/heroes-service#6]
I have been round and round with this, the main.go file fails to find the fixtures/artifacts/chainhero.channel.tx file every time even if I make the path explicit, have you seen this before? any thoughts? Im on Mac.. this is the file on visual code with everything present and also checked the go path many times.. not sure what else to try here..
<img width="894" alt="screen shot 2018-03-11 at 20 21 21" src="https://user-images.githubusercontent.com/28452476/37258074-021c8998-256a-11e8-99eb-a32b8489b5dc.png">

**Comment by MaximeAubanel** [comment]
Hello Sir,

Your issue is quite disturbing. Never seen this before.
Did you try to directly clone the repository instead of following the tutorial ?

Please provide me your os details. I'll try to recreate your issue on a virtual machine.

**Comment by antitoine** [comment]
I'm closing this issue as there's no news from @beshogun .
