### ISSUE TITLE
Unable to initialize the Fabric SDK

### ISSUE THREAD

**Issue by AkshitKrNagpal** [chainHero/heroes-service#7]
When running `make` I am getting this error after `Environnement Up`in log.

`Unable to initialize the Fabric SDK: failed to create new resource management client: unable to get client provider context: unable to retrieve configuration from SDK: must provide default organisation name in configuration`

**Comment by MaximeAubanel** [comment]
Hello Sir,

Did you follow the tutorial step by step or did you directly clone the repository and execute the command `make` ?

Moreover can you please tell us on which distro are you.

**Comment by AkshitKrNagpal** [comment]
@MaximeAubanel 
Thanks for the response.
I am following the tutorial. Everything before this worked as described in the tutorial.

I am using macOS High Sierra 10.13.3 (Sorry I should have mentioned it earlier)

**Comment by MaximeAubanel** [comment]
Alright.

Can you tell me exactly at what step did this message appeared ?

**Comment by AkshitKrNagpal** [comment]
After creating `Gopkg.toml`, I created Makefile (Just copied and pasted).
Then I executed `make`.

I didn't execute them stepwise at first but when I did, executing `./heroes-service` gave me this error.
` [fabric_sdk_go] 2018/04/01 00:33:46 UTC - config.initConfig -> INFO config fabric_sdk_go logging level is set to: INFO
Unable to initialize the Fabric SDK: failed to create channel: create channel failed: failed broadcast to orderer: Orderer Server Status Code: (400) BAD_REQUEST. Description: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x45a86dd]

goroutine 1 [running]:
github.com/chainHero/heroes-service/blockchain.(*FabricSetup).InstallAndInstantiateCC(0xc42019edd0, 0x28, 0xc420179e90)
	/Users/akshitkrnagpal/go/src/github.com/chainHero/heroes-service/blockchain/setup.go:102 +0x1ad
main.main()
	/Users/akshitkrnagpal/go/src/github.com/chainHero/heroes-service/main.go:37 +0x1f1
`

I cloned this GitHub repo also, I got the same error.

**Comment by MaximeAubanel** [comment]
Hang on. So you are telling me that when you clone the repository then execute ``make``. You got this error too ?

**Comment by AkshitKrNagpal** [comment]
Yes. Just cloned it when you asked me.

**Comment by AkshitKrNagpal** [comment]
@MaximeAubanel 
I don't know what happened but my mac restarted and now both my code and the direct clone of this repo are working.
Thanks for your help.
I'll close this.

Also, can you have a look at #8 pull request?
